#!/usr/bin/env python3
import time

from color import Color
from matrix import Matrix

m = Matrix()

try:
    while True:
        m.fill_matrix(Color().red())
        m.render()
        time.sleep(.5)

        m.fill_matrix(Color().blue())
        m.render()
        time.sleep(.5)

        m.fill_matrix(Color().green())
        m.render()
        time.sleep(.5)

        m.fill_matrix(Color().white())
        m.render()
        time.sleep(.5)

        for i in range(255):
            m.fill_matrix(Color(i, 0, 0))
            m.render()
            time.sleep(.05)

        for i in range(255):
            m.fill_matrix(Color(0, i, 0))
            m.render()
            time.sleep(.05)

        for i in range(255):
            m.fill_matrix(Color(0, 0, i))
            m.render()
            time.sleep(.05)

        for i in range(255):
            m.fill_matrix(Color(i, i, 0))
            m.render()
            time.sleep(.05)

        for i in range(255):
            m.fill_matrix(Color(i, 0, i))
            m.render()
            time.sleep(.05)

except KeyboardInterrupt:
    m.fill_matrix()
    m.render()
    time.sleep(.05)
