#!/usr/bin/env python3
import time

from color import Color
from matrix import Matrix

m = Matrix()

try:
    while True:
        m.fill_matrix(Color().red())
        m.render()
        time.sleep(.05)

        m.fill_matrix(Color().blue())
        m.render()
        time.sleep(.05)

        m.fill_matrix(Color().green())
        m.render()
        time.sleep(.05)

        m.fill_matrix(Color().white())
        m.render()
        time.sleep(.05)

        for r in range(255):
            for g in range(255):
                for b in range(255):
                    m.fill_matrix(Color(r, g, b))
                    m.render()
                    time.sleep(.05)

except KeyboardInterrupt:
    m.fill_matrix()
    m.render()
    time.sleep(.05)
